services:
    mongodb:
        image: mongo:5.0.26
        container_name: mongodb-test
        ports:
            - '27016:27017'
        volumes:
            - './config/mongod.conf:/data/configdb/mongod.conf:ro'
            - './data:/data/db'
            - 'log:/var/log/mongodb'
        command: ['/usr/bin/mongod', '-f', '/data/configdb/mongod.conf']
        restart: always
volumes:
    log: null
